### ISSUE TITLE
[TIL] 양희제 / 2022-12-15

### ISSUE THREAD

**Issue by HeeJeYang** [HeeJeYang/project_name#36]
### ❓ 어떻게 해야 화면 크기에 맞는 반응형 디자인을 잘 이뤄낼 수 있을까?

- 저번 프로젝트 때 이루지 못했던 반응형 디자인을 구현해보려 하는데 여전히 많은 어려움이 존재한다. 막연하게 퍼센트로 주게 되면 화면이 많이 작아졌을 때 중요한 컴포넌트 또한 같이 작아지게 된다. 따라서 특정 Viewport 미만일 땐 아예 컴포넌트 구조를 바꿔버리고 싶어서 찾아봤던 해결 방법에 대해 적어보고자 한다!

**1. 미디어쿼리 이용**

- 구체적인 조건을 제시하여 필요한 스타일을 각각 적용시킬 수 있도록 미디어 타입을 확장한 것
- 반응형 웹 디자인의 핵심 부분으로, 프론트엔드를 지망한다면 필수로 알아둬야 한다!
- 사용법

```css
@media (min-width: 768px) {

  .SignUp .big_screen {
    width: 100%;
    height: 100%;

    display: flex;
  }

  .SignUp .big_screen .signup_poster_wrapper {
    width: 50%;
    height: 100%;
  }

  .SignUp .big_screen .signup_poster_wrapper img {
    width: 100%;
    height: 100%;
  }

  .SignUp .big_screen .signup_form_wrapper {
    width: 50%;
    height: 100%;
    position: relative;
  }
}

@media (max-width: 768px) {
  .SignUp .small_screen {
    width: 100%;
    height: 100%;
    position: relative;
  }
}
```

위 예처럼 해상도를 기준으로 다른 디자인을 부여할 수 있다!

- 추가 문법
 
<img width="950" alt="image" src="https://user-images.githubusercontent.com/89143804/207649680-2e72757a-c4a2-478a-92a6-a78c525d0760.png">

미디어 쿼리를 잘 활용하고 싶다면 [여기](https://velog.io/@pyo-sh/React-Responsive) 참조

**2. react-responsive에서 제공하는 useMediaQuery 이용**

- 라이브러리를 이용하여 mediaquery를 좀 더 편하게 이용할 수 있게 해줌.
- 사용법

```javascript
import React from "react";
import { useMediaQuery } from "react-responsive";

// Components
import SignUpForm from "../components/Forms/SignUpForm";

const SignUp = () => {
  const isBigScreen = useMediaQuery({ query: "(min-width: 768px)" });
  const isSmallScreen = useMediaQuery({ query: "(max-width: 768px)" });
  return (
    <div className="SignUp">
      {isBigScreen && (
        <div className="big_screen">
          <div className="signup_poster_wrapper">
            <img
              src={`${process.env.PUBLIC_URL}/assets/poster/poster1.png`}
              alt="signup_poster"
            />
          </div>
          <div className="signup_form_wrapper">
            <SignUpForm />
          </div>
        </div>
      )}
      {isSmallScreen && (
        <div className="small_screen">
            <SignUpForm />
        </div>
      )}
    </div>
  );
};

export default SignUp;
```

위 코드는 뷰포트가 768px 미만일 때를 isSmallScreen으로 두고, 768px 이상일 때를 isBigScreen으로 둔 뒤, 각각의 경우에 표시해줄 html 요소를 따로 표현해준 모습이다.

따라서 뷰포트의 길이에 따라 **같은 컴포넌트 구조일 때는 퍼센트로 반응형 처리를 해주고, 다른 컴포넌트 구조로 바뀌어야 할 땐 이에 대한 breakpoint를 설정**하여 알맞은 처리를 해주면 될 것 같다.
